"""empty message

Revision ID: 44734ab7b842
Revises: e9f438d26b4f
Create Date: 2020-03-02 21:15:49.958446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44734ab7b842'
down_revision = 'e9f438d26b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
